CREATE TABLE EXECUTOR(
ID INT PRIMARY KEY,
NAME VARCHAR(25) NOT NULL
);

CREATE TABLE ALBUM(
ID INT PRIMARY KEY,
NAME VARCHAR(25) NOT NULL,
GENRE VARCHAR(15),
EXECUTOR_ID INT,
CONSTRAINT EXEC_FK FOREIGN KEY(EXECUTOR_ID) REFERENCES EXECUTOR(ID)
);

CREATE TABLE COMPOSITION(
ID INT PRIMARY KEY,
NAME VARCHAR(40) NOT NULL,
LENGTH INT,
ALBUM_ID INT,
CONSTRAINT ALBUM_FK FOREIGN KEY(ALBUM_ID) REFERENCES ALBUM(ID)
);

DROP TABLE COMPOSITION;
DROP TABLE ALBUM;
DROP TABLE EXECUTOR;
DROP SEQUENCE EXEC_SEQ;
DROP SEQUENCE ALBUM_SEQ;
DROP SEQUENCE COMP_SEQ;

CREATE SEQUENCE COMP_SEQ
INCREMENT BY 1
MINVALUE 1
START WITH 1;

CREATE SEQUENCE ALBUM_SEQ
INCREMENT BY 1
MINVALUE 1
START WITH 1;

CREATE SEQUENCE EXEC_SEQ
INCREMENT BY 1
MINVALUE 1
START WITH 1;

INSERT INTO EXECUTOR VALUES (NEXTVAL('EXEC_SEQ'), 'Люмен'),
                            (NEXTVAL('EXEC_SEQ'), 'Агата Кристи'),
                            (NEXTVAL('EXEC_SEQ'), 'Сплин'),
                            (NEXTVAL('EXEC_SEQ'), 'Би-2');

INSERT INTO ALBUM VALUES (NEXTVAL('ALBUM_SEQ'), 'Би-2', 'рок', 1),
                         (NEXTVAL('ALBUM_SEQ'), 'Лабиринт', 'рок', 4),
                         (NEXTVAL('ALBUM_SEQ'), 'Б1', 'металл', 2),
                         (NEXTVAL('ALBUM_SEQ'), 'В1', 'фолк', 1),
                         (NEXTVAL('ALBUM_SEQ'), 'В1', 'неизвестен', 2),
                         (NEXTVAL('ALBUM_SEQ'), 'Г1', 'реп', 3);
							
INSERT INTO COMPOSITION VALUES (NEXTVAL('COMP_SEQ'), 'Полковнику никто не пишет', 100, 1),
                               (NEXTVAL('COMP_SEQ'), 'Варвара', 90, 1),
                               (NEXTVAL('COMP_SEQ'), 'Лабиринт', 85, 2),
                               (NEXTVAL('COMP_SEQ'), 'Трек4', 111, 4),
                               (NEXTVAL('COMP_SEQ'), 'Трек5', 220, 5);
							   						
--1
SELECT CONCAT(NAME,',',LENGTH) AS Song_Details FROM COMPOSITION;			
--2
SELECT NAME, LENGTH FROM COMPOSITION WHERE LENGTH NOT BETWEEN 5 AND 10 ORDER BY LENGTH DESC;
SELECT NAME, LENGTH FROM COMPOSITION WHERE LENGTH < 5 OR LENGTH > 10 ORDER BY LENGTH DESC;
--3
SELECT NAME FROM EXECUTOR WHERE NAME LIKE '_е%' AND ID IN(1111111,2222222);
SELECT NAME FROM EXECUTOR WHERE NAME LIKE '_е%' AND (ID = 1111111 OR ID = 2222222);
--4
SELECT MIN(LENGTH) as min, MAX(LENGTH) as max, AVG(LENGTH) as avg, SUM(LENGTH) as sum, COUNT(*) as all FROM COMPOSITION;
--5
SELECT NAME FROM ALBUM WHERE EXECUTOR_ID = (SELECT ID FROM EXECUTOR WHERE NAME = 'Би-2');
--6
SELECT A.NAME, C.NAME FROM ALBUM AS A, COMPOSITION AS C WHERE (C.LENGTH = (SELECT MIN(C.LENGTH) FROM COMPOSITION AS C WHERE C.LENGTH > 5 AND A.ID = C.ALBUM_ID)) AND A.ID = C.ALBUM_ID;
--7
SELECT NAME, LENGTH FROM COMPOSITION WHERE LENGTH > (SELECT AVG(LENGTH) FROM COMPOSITION);
--8
SELECT NAME, LENGTH FROM COMPOSITION WHERE LENGTH > ANY(SELECT LENGTH FROM COMPOSITION WHERE ALBUM_ID = 1);
--9
SELECT NAME, LENGTH FROM COMPOSITION WHERE LENGTH > ALL(SELECT LENGTH FROM COMPOSITION WHERE ALBUM_ID = 1);
--10
SELECT NAME FROM COMPOSITION WHERE LENGTH = (SELECT LENGTH FROM COMPOSITION WHERE NAME = 'Трек123') AND NAME <> 'Трек123';
